// Generated by CoffeeScript 1.6.2
(function() {
  var app, expect, request;

  expect = require('chai').expect;

  app = require('../server');

  request = require('supertest');

  describe("Routes", function() {
    return describe("/:name", function() {
      return it("should be ok", function() {
        return request(app).get('/').expect(200).end(function(err, res) {
          if (err) {
            console.log(err);
          }
          return done();
        });
      });
    });
  });

}).call(this);
