// Generated by CoffeeScript 1.6.2
(function() {
  var async, client, findPerson, mongo;

  mongo = require('mongodb');

  async = require('async');

  client = mongo.MongoClient;

  findPerson = function(restrictions, callback) {
    return async.waterfall([
      function(done) {
        return client.connect("mongodb://localhost:27017/noname_app", done);
      }, function(db, done) {
        console.log("we are connected");
        return db.collection('people', done);
      }, function(peopleCollection, done) {
        return peopleCollection.findOne(restrictions, done);
      }, function(docs, done) {
        return done(null, docs);
      }
    ], function(err, person) {
      if (err) {
        callback(err);
      }
      return callback(null, person);
    });
  };

  module.exports.findPerson = findPerson;

}).call(this);
