// Generated by CoffeeScript 1.6.2
(function() {
  var client, mongo;

  mongo = require('mongodb');

  client = mongo.MongoClient;

  client.connect("mongodb://localhost:27017/noname_app", function(err, db) {
    if (err) {
      console.log("there was an error");
    }
    if (!err) {
      return console.log("we are connected!");
    }
  });

}).call(this);
