// Generated by CoffeeScript 1.6.2
(function() {
  var app, db, express;

  express = require('express');

  db = require('./dbConnection');

  app = express();

  app.get('/:name', function(req, res) {
    return db.findPerson({
      name: req.params.name
    }, function(err, person) {
      return res.send("<h1>" + person.name + "</h1>");
    });
  });

  app.listen(3000);

}).call(this);
