// Generated by CoffeeScript 1.6.2
(function() {
  var express;

  express = require('express');

  app.express();

  app.get('/', function(req, res) {
    return res.send('Hello World');
  });

  app.listen(3000);

}).call(this);
