// Generated by CoffeeScript 1.6.2
(function() {
  var app, db, express;

  express = require('express');

  db = require('./dbConnection');

  app = express();

  app.get('/:name', function(req, res) {
    return db.findPerson({
      name: req.params.name
    }).then(function(data) {
      return res.send(data);
    });
  });

  app.listen(3000);

}).call(this);
