// Generated by CoffeeScript 1.7.1
(function() {
  var client, conString, pg;

  pg = require('pg');

  conString = "postgres://localhost/nodetest";

  client = new pg.Client(conString);

  client.connect(function(err) {
    if (err) {
      console.log(err.message);
    }
    return console.log('success');
  });

  client.query("INSERT INTO users " + "(name, age) VALUES ($1, $2)", ['Mike', 39]);

}).call(this);
